// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d216440-f620-4062-97bf-5377206be1fd"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 7, 7, 2, 18, 39, 562, DateTimeKind.Utc).AddTicks(8949),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("993a54de-4565-4ecf-8fab-159abf1b01b5"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2023, 8, 7, 2, 18, 39, 562, DateTimeKind.Utc).AddTicks(8972),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("884ec796-39fa-4af2-86a2-5c00d2f2bb32"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2023, 10, 7, 2, 18, 39, 562, DateTimeKind.Utc).AddTicks(8975),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("0e7a8f40-243b-45f1-b35d-d263894d2229"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2023, 11, 7, 2, 18, 39, 562, DateTimeKind.Utc).AddTicks(8987),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("b87a8fa8-3ae8-49c5-8307-8516677aafcd"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 12, 7, 2, 18, 39, 562, DateTimeKind.Utc).AddTicks(8989),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("ddbb54a8-75de-4a21-b6a7-c901b767bb07"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 1, 7, 2, 18, 39, 562, DateTimeKind.Utc).AddTicks(8995),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("b9fdc5dd-3236-49ca-82ad-35e92d676b6d"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 2, 7, 2, 18, 39, 562, DateTimeKind.Utc).AddTicks(8998),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("8ed0f362-f7b1-4256-ab58-0b84f04b23b6"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 3, 7, 2, 18, 39, 562, DateTimeKind.Utc).AddTicks(9000),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("a7c51937-26f4-47b0-9c31-03b8c396578a"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2024, 4, 7, 2, 18, 39, 562, DateTimeKind.Utc).AddTicks(9002),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("a604d90b-7576-4765-ba88-9cce610a982e"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2024, 5, 7, 2, 18, 39, 562, DateTimeKind.Utc).AddTicks(9006),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
